toastal does **__not__** support GitHub as a platform
=====================================================
:abbr-EEE: pass:[<abbr title="embrace, extend, extinguish">EEE</abbr>]
:abbr-FLOSS: pass:[<abbr title="free, libre, open-source software">FLOSS</abbr>]
:abbr-GNU: pass:[<abbr title="GNU’s not Unix!">GNU</abbr>]
:abbr-GPL: pass:[<abbr title="GNU Public License">GPL</abbr>]
:abbr-NPM: pass:[<abbr title="Node Package Manager">NPM</abbr>]
:abbr-WSL: pass:[<abbr title="Windows Subsystem Linux">WSL</abbr>]

* Git should be decentralized, not requiring a specific platform. While there are some enhancements to the process, there should not be a barrier beyond email if a user does not wish to share data with GitHub. Due to this, many projects are stuck on GitHub through vendor-lock-in. As a user, I must fork your project on GitHub to submit a merge request. Worse is some communities, like Elm and Nix have tied their user identity to this closed system.
* GitHub is trying to make code unnecessarily ‘social’ which doesn’t need to exist. We don’t need targeted advertising for other projects or people being overly worried about how colorful status progress bars are. One start is using `github.com##aside[aria-label="Explore"], #dashboard.dashboard .reactions-with-gap` as a uBlock Origin rule to hide random projects on your home screen while leaving Explore from the menu in tact as well as removing reactions from the Dashboard.
* GitHub is owned by Microsoft—the same company that used link:https://en.wikipedia.org/wiki/Embrace,_extend,_and_extinguish[embrace, extend, extinguish ({abbr-EEE})] in the past to ruin software as a whole. Microsoft is trying to further monopolize with Azure, Codespaces, Visual Studio (regular & Code), {abbr-NPM}, Sponsors, and trying to steal mindshare from free software with Windows Subsystem Linux ({abbr-WSL}). Over time, they have been pushing for tighter and tighter integrations, and we can assume eventually they will see no need to afford any interop and more proprietary extensions will be added. This is what happens under capitalism.
* GitHub is closed source. While Git is open and many of the projects on GitHub are, GitHub is not. If you have a problem, you can’t just send up a fix nor can you fork and self-host the project. Putting your business’s data on it, assures no protections.
* GitHub’s Copilot should not be supported and it’s spitting out code that violates {abbr-GPL}, copies bugs, and isn’t there to help you. As it is meant to be paid in the future, right now, _you_ the user are training it and not getting paid for your service despite the stated future being that it will be a product sold back to you. While lessening the barrier to entry for programming could be good, training on all of our open code behind a closed platform and captital-hungry entity to sell which isn’t in the spirit of open source or free software.

We’ve seen most {abbr-GPL}, {abbr-GNU}, and privacy-oriented projects move to alternatives because they want to respect their users and the spirit of open source. I hope to see your projects move to one of the alternatives soon too.

== What can I as a user do?

* Use an alternative Git code forge
+
--
   Git-supporting Code Forge Alternatives::
   * https://sr.ht/[Sourcehut] - self-hostable AGPL service where using their hosted basics are free (including mailing lists), but CI is paid, however it is not VC-funded nor does it have investors or shareholders to appease
   * https://savannah.gnu.org/[{abbr-GNU} Savannah] - for {abbr-FLOSS} software where your projects need to be approved as such
   * https://gitea.io/[Gitea] - self-hosted, {abbr-FLOSS} GitHub clone essentially
   * https://codeberg.org/[Codeberg] - Gitea hosted by a German non-profit
   * https://git.zx2c4.com/cgit/about/[cgit] - tiny, self-hosted {abbr-GPL} Git UI
   * https://gitlab.com/[GitLab] - free, Ruby-based forge support full build pipeline and self-hostable (however are VC-funded and have investors to appease, so we’ll see about the future)
--   
* Ask your code communities and workplace to switch to an alternative code forge or officially support a mirror on an alternative. If that cannot be done, ask your code communities and workplace to at least allow additions to its larger ecosystem from these alternatives (plugins, packages, etc.).
* Oppose all attempts to standardize, endorse, or weigh anything in GitHub’s specific favor (like shorthands for packages)

== Then why are you even here?

I support open source projects and a lot of it is here unfortunately. I care more about the spirit of open source projects than my personal stance on where the code is hosted, but I really wish they were elsewhere. You can’t have any migration conversations without contributing to projects in good faith. To a lot of people GitHub is seen as a default and alternatives were never considered.

Also let’s get mad that GitHub strips out `<abbr>` tags from rendered documents such as this even though these tags would help accessibility.

== Where can I find your code now?

* Sourcehut (primary): https://git.sr.ht/~toastal/
* GitLab: https://gitlab.com/toastal
* Codeberg: https://codeberg.org/toastal/
