toastal does _not_ support GitHub as a platform
===============================================

* Git should be decentralized, not requiring a specific platform. While there are some enhancements to the process, there should not be a barrier beyond email if a user does not wish to share data with GitHub. Due to this, many projects are stuck on GitHub through vendor-lock-in. As a user, I must fork your project on GitHub to submit a merge request. Worse is some communities, like Elm and Nix have tied their user identity to this closed system.
* GitHub is trying to make code unnecessarily ‘social’ which doesn’t need to exist. We don’t need target advertising for other projects or people being overlay worried about how colorful status progress bars are.
* GitHub is owned by Microsoft—the same company that used _embrace, extend, extinguish_ in the past to ruin software as a whole. Microsoft is trying to further monopolize with Azure, Visual Studio (regular & Code), NPM, and trying to steal mindshare from free software with Window Subsystem Linux. Over time, they have been pushing for tighter and tighter integrations.
* GitHub is closed source. While Git is open and many of the projects on GitHub are, GitHub is not. If you have a problem, you can’t just send up a fix nor can you fork and self-host the project.
* GitHub is in the business of tracking and sharing data of its users.
* GitHub’s Copilot should not be supported and it’s spitting out code that violates GPL, copies bugs, and isn’t there to help you. As it is meant to be paid in the future, right now, _you_ the user are training it and not getting paid for your service. While lessening the barrier to entry for programming could be good, training on all of our open code behind a closed platform and captital-hungry entity to sell which isn’t in the spirit of open source or free software.

We’ve seen most GPL and GNU and privacy-oriented projects move to alternatives because they want to respect their users and the spirit of open source. I hope to see your projects move to one of the alternatives soon too.

Git-supporting Code Forge Alternatives::
* https://sr.ht/[Sourcehut]
* https://savannah.gnu.org/[GNU Savannah]
* https://gitea.io/[Gitea]
* https://git.zx2c4.com/cgit/about/[cgit]
* https://codeberg.org/[Codeberg]
* https://gitlab.com/[GitLab]
