toastal does **__not__** support GitHub as a platform
=====================================================

[quote,Matt Lee,https://www.linuxjournal.com/content/opinion-github-vs-gitlab]
____
Choosing proprietary tools and services for your free software project ultimately sends a message to downstream developers and users of your project that freedom of all users—developers included—is not a priority.
____

:abbr-CD: pass:[<abbr title="continous delivery">CD</abbr>]
:abbr-CI: pass:[<abbr title="continous integration">CI</abbr>]
:abbr-EEE: pass:[<abbr title="embrace, extend, extinguish">EEE</abbr>]
:abbr-FLOSS: pass:[<abbr title="free, libre, open-source software">FLOSS</abbr>]
:abbr-FOMO: pass:[<abbr title="fear of missing out">FOMO</abbr>]
:abbr-FOSS: pass:[<abbr title="free, open-source software">FLOSS</abbr>]
:abbr-GNU: pass:[<abbr title="GNU’s not Unix!">GNU</abbr>]
:abbr-GPL: pass:[<abbr title="GNU Public License">GPL</abbr>]
:abbr-HN: pass:[<abbr title="Hacker News">HN</abbr>]
:abbr-UI: pass:[<abbr title="user interface">UI</abbr>]
:abbr-VCS: pass:[<abbr title="venture capital">VC</abbr>]
:abbr-VCS: pass:[<abbr title="version control system">VCS</abbr>]
:abbr-WSL: pass:[<abbr title="Windows Subsystem Linux">WSL</abbr>]

* Git should be decentralized, not requiring a specific platform. While there are some enhancements to the process, there should not be a barrier beyond email if a user does not wish to share data with GitHub. Due to this, many projects are stuck on GitHub through vendor-lock-in. As a user, I must fork your project on GitHub to submit a merge request. Worse is some communities, like Elm and Nix have tied their user identity to this closed system.
* GitHub is trying to make code unnecessarily ‘social’ which doesn’t need to exist. We don’t need targeted advertising for other projects or people being overly worried about how colorful status progress bars are. Plug: I have created a https://git.sr.ht/~toastal/github-less-social[uBlock Origin list] to help declutter your page.
* GitHub is owned by Microsoft—the same company that used link:https://en.wikipedia.org/wiki/Embrace,_extend,_and_extinguish[embrace, extend, extinguish ({abbr-EEE})] in the past to ruin software as a whole. Microsoft is trying to further monopolize with Azure, Codespaces, Visual Studio (regular & Code), npm, Sponsors, and trying to steal mindshare from free software with Windows Subsystem Linux ({abbr-WSL}) and your org with Teams. Over time, they have been pushing for tighter and tighter integrations, and we can assume eventually they will see no need to afford any interop and more proprietary extensions will be added. This is what happens under capitalism and publicly traded companies are legally obligated to make profits for the shareholders and have no allegience to helping the users if it does not help profit.
* GitHub is closed source. While Git is open and many of the projects on GitHub are, GitHub is not. If you have a problem, you can’t just send up a fix nor can you fork and self-host the project. Putting your business’s data on it assures no protections.
* The API of GitHub is https://github.com/MichaelMure/git-bug/issues/749#issuecomment-1072991272[not very stable]. So while you can tool your way around simple things like email, it is not as simple with GitHub.
* Search results are gated. When you search a project on Microsoft GitHub and looking to use the “Code” section, when you are not authenticated you will get a `?` results and clicking “Code” will bring you too a login. Users may not search code without a Microsoft account.
* GitHub’s Copilot should not be supported and it’s controversially either spitting out code that violates {abbr-GPL} or as one lawyer said all outputs are derivative and *must* be in the public domain (so your code may have future legal issues), it copies bugs, and isn’t there to help more than you help train it. +++<del>As it is meant to be paid in the future, right now, <em>you</em> the user are training it and not getting paid for your service despite the stated future being that it will be</del>+++ It is now a product sold back to you. While lessening the barrier to entry for programming could be good, training on all of our open code behind a closed platform, closed data, and captital-hungry entity to sell isn’t in the spirit of open source or free software. Currently the project https://githubcopilotlitigation.com[is under litigation].
* The $500k donation PR stunt is an attempt to get more people to buy into their payment platform (which will take an additional 10% cut beyond an other transaction fees). Naturally this was paid out only to folks that signed up for their payment service in an attempt to bring others in on {abbr-FOMO} and further monopolize the source code platform.
* GitHub has a terrible landing page experience. Does your {abbr-CI} build status badges in your README **really** help me understand the how/what/why of your project, or are you bloating the README because GitHub doesn’t give you more flexible ways to mark up your projects? GitLab has badges as a project setting. Sourcehut lets you upload arbiritrary (sanitized) HTML to the landing page. As an {abbr-HN} user eloquently phrased it, the README has become a RENDERME and thusly GitHub has ruined the README. A lot of the recent _good_ ideas coming into GitHub have been borrowed from its competitors (Mermaid docs, integrated {abbr-CI}/{abbr-CD}). Now they want https://github.com/orgs/github-community/discussions/16925[to break Markdown standards further] despite existing proposals to CommonMark with more GitHub-flavored nonsense because they are a bully and no longer feel they need to cooperate.

We’ve seen most {abbr-GPL}, {abbr-GNU}, and privacy-oriented projects move to alternatives because they want to respect their users and the spirit of open source. I hope to see your projects move to one of the alternatives soon too.

== What can I as a user do today?

* Use an alternative Git code forge
+
--
Git-supporting Code Forge Alternatives::
   https://sr.ht/[SourceHut]:: self-hostable AGPL service where using their hosted basics are free (including mailing lists and an IRC bouncer), but {abbr-CI} is paid, however it is not VC-funded nor does it have investors or shareholders to appease
	https://savannah.gnu.org/[{abbr-GNU} Savannah]:: for {abbr-FLOSS} software where your projects need to be approved as such
	https://forgejo.org/[Forgejo]:: self-hosted, {abbr-FLOSS} GitHub clone essentially
	https://codeberg.org/[Codeberg]:: Gitea hosted by a German non-profit
	https://git.zx2c4.com/cgit/about/[cgit]:: tiny, self-hosted {abbr-GPL} Git {abbr-UI}
	https://gitlab.com/[GitLab]:: free, open-core, Ruby-based forge support with full build pipeline and self-hostable community edition (however are {abbr-VC}-funded and is publicly traded so they have investors to appease, so we’ll see about the future)
 
Non-Git VCS Code Forge Alternatives::
   http://darcs.net[darcs]:: “Darcs is a free and open source, cross-platform version control system, […] with a very different approach: focus on changes rather than snapshots. Darcs offers a freer way of working, and a simpler user interface.”
--
* Ask your code communities and workplace to switch to an alternative code forge or officially support a mirror on an alternative. If that cannot be done, ask your code communities and workplace to at least allow additions to its larger ecosystem from these alternatives (plugins, packages, etc.).
* Oppose all attempts to standardize, endorse, or weigh anything in GitHub’s specific favor (like shorthands for packages)
* Make sure educational institutions aren’t requiring students to sign up from proprietary accounts. It’s bad enough that the next generation continues to be trained in Adobe Suite and Microsoft Office instead of {abbr-FLOSS} options, but now Git and other {abbr-VCS} are in the same boat where fundamentals can be learned that don’t require a proprietary service (and universites in particular have the resources to self-host at least cgit).

== Then why are you even here?

I support open source projects and a lot of it is here unfortunately. I care more about the spirit of open source projects than my personal stance on where the code is hosted, but we really need to get more code off this platform. You can’t have any migration conversations without contributing to projects in good faith. To a lot of people GitHub is seen as a default and alternatives were never considered.

Also let’s get mad that GitHub strips out `<abbr>` tags from rendered documents such as this even though these tags would help accessibility.

== Where can I find your code now?

SourceHut (primary):: https://sr.ht/~toastal/
GitLab:: https://gitlab.com/toastal
Codeberg:: https://codeberg.org/toastal/
