⚠️ toastal does **__not__** support GitHub as a platform
========================================================

:abbr-EEE: pass:[<abbr title="embrace, extend, extinguish">EEE</abbr>]
:abbr-GNU: pass:[<abbr title="GNU’s not Unix!">GNU</abbr>]
:abbr-GPL: pass:[<abbr title="GNU Public License">GPL</abbr>]
:abbr-NPM: pass:[<abbr title="Node Package Manager">NPM</abbr>]
:abbr-WSL: pass:[<abbr title="Windows Subsystem Linux">WSL</abbr>]

* Git should be decentralized, not requiring a specific platform. While there are some enhancements to the process, there should not be a barrier beyond email if a user does not wish to share data with GitHub. Due to this, many projects are stuck on GitHub through vendor-lock-in. As a user, I must fork your project on GitHub to submit a merge request. Worse is some communities, like Elm and Nix have tied their user identity to this closed system.
* GitHub is trying to make code unnecessarily ‘social’ which doesn’t need to exist. We don’t need target advertising for other projects or people being overlay worried about how colorful status progress bars are. One start is using `github.com##aside[aria-label="Explore"], #dashboard.dashboard .reactions-with-gap` as a uBlock Origin rule to hide random projects on your home screen while leaving Explore from the menu in tact as well as removing reactions from the Dashboard.
* GitHub is owned by Microsoft—the same company that used link:https://en.wikipedia.org/wiki/Embrace,_extend,_and_extinguish[embrace, extend, extinguish ({abbr-EEE})] in the past to ruin software as a whole. Microsoft is trying to further monopolize with Azure, Codespaces, Visual Studio (regular & Code), {abbr-NPM}, Sponsors, and trying to steal mindshare from free software with Windows Subsystem Linux ({abbr-WSL}). Over time, they have been pushing for tighter and tighter integrations.
* GitHub is closed source. While Git is open and many of the projects on GitHub are, GitHub is not. If you have a problem, you can’t just send up a fix nor can you fork and self-host the project. Putting your business’s data on it, assures no protections.
* GitHub’s Copilot should not be supported and it’s spitting out code that violates {abbr-GPL}, copies bugs, and isn’t there to help you. As it is meant to be paid in the future, right now, _you_ the user are training it and not getting paid for your service. While lessening the barrier to entry for programming could be good, training on all of our open code behind a closed platform and captital-hungry entity to sell which isn’t in the spirit of open source or free software.

We’ve seen most {abbr-GPL} and {abbr-GNU} and privacy-oriented projects move to alternatives because they want to respect their users and the spirit of open source. I hope to see your projects move to one of the alternatives soon too.

== What can I as a user do?

* Use an alternative Git code forge
+
--
   Git-supporting Code Forge Alternatives::
   * https://sr.ht/[Sourcehut]
   * https://savannah.gnu.org/[GNU Savannah]
   * https://gitea.io/[Gitea]
   * https://git.zx2c4.com/cgit/about/[cgit]
   * https://codeberg.org/[Codeberg]
   * https://gitlab.com/[GitLab]
--   
* Ask your code communities and workplace to switch to an alternative code forge or officially support a mirror on an alternative. If that cannot be done, ask your code communities and workplace to at least allow additions to its larger ecosystem from these alternatives.
* Oppose all attempts to standardize, endorse, or weigh anything in GitHub’s specific favor (like shorthands for packages)

== Then why am I even here?

I support open source code and a lot of it is regrettable here. I care more about these projects than my person stance, but I really wish they were elsewhere. You can’t have these migration conversations without contributing to projects in good faith.

Also let’s get mad that GitHub strips out `<abbr>` tags from rendered documents even though these tags would help accessibility.
